import Head from "next/head";
import { useEffect, useState } from "react";

// components
import Navigation from "../components/Navigation";
import CardWallet from "../components/CardWallet";
import CoinsShower from "../components/CoinsShower";

import { Button } from "react-bootstrap";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Criptomonedas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <CoinsShower coins={data} />
      <Button variant="primary" className="ml-5 mt-1">
        Add Wallet
      </Button>
      <CardWallet />
    </>
  );
}

export const getServerSideProps = async () => {
  const apiKey = "9e0ecf94f37cfbdd";
  const res = await fetch(
    `https://coinlib.io/api/v1/coinlist?key=${apiKey}&page=1&order=rank_asc`
  );
  const response = await res.json();
  const data = response.coins.slice(0, 20);
  // Pass data to the page via props
  return { props: { data } };
};
